
services:
  backend:
    build:
      context: ./backend
      dockerfile: EventApp/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: "EventAppdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - ./postgres-backup:/docker-entrypoint-initdb.d
    ports:
      - "5438:5432"

volumes:
  postgres-data:

