
services:
  backend:
    build:
      context: ./backend
      dockerfile: EventApp/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - APP_UID=1000
    #   - ConnectionStrings__DefaultConnection=Host=database;Database=EventAppdb;Username=postgres;Password=123;
    # depends_on:
    #   - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: "EventAppdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - ./postgres-backup:/docker-entrypoint-initdb.d
    ports:
      - "5438:5432"

volumes:
  postgres-data:

# services:
#   postgres:
#     container_name: postgres
#     image: postgres:latest
#     environment:
#       POSTGRES_DB: "db"
#       POSTGRES_USER: "postgres"
#       POSTGRES_PASSWORD: "123"
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     ports:
#       - "5438:5432"

# volumes:
#   postgres-data:
